version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "s3kata"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16ky9oswuazxh"
s3_prefix = "s3kata"
region = "us-west-2"
profile = "reza"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
